adminapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from adminapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name='login'),
    path('index', views.index, name='index'),
    path('logout', views.logout_admin, name='logout_admin'),
    path('contact', views.Show_contact, name='contact'),
    path('appointment', views.Show_Appointment, name='appointment'),
    path('edit_user_appointments/<int:id>', views.edit_appointments, name='edit_user_appointments'),
    path('demo', views.demo, name='demo'),
    
    path('reviews', views.reviews, name='reviews'),
    
    path('clients', views.client, name='clients'),
    path('add_client', views.add_or_edit_client, name='add_client'),
    path('add_or_edit_client/<int:pk>', views.add_or_edit_client, name='edit_client'),
    path('delete_client/<int:id>', views.delete_client, name='delete_client'),
    # path('edit_client/<int:id>', views.edit_client, name='edit_client'),
    # path('add_new_client', views.add_new_client, name='add_new_client'),
    
    
    path('lawyer', views.lawyers, name='lawyers'),
    path('add_new_lawyer', views.add_new_lawyer, name='add_new_lawyer'),
    path('delete_lawyer/<int:id>', views.delete_lawyer, name='delete_lawyer'),    
    path('edit_lawyer/<int:id>', views.edit_lawyer, name='edit_lawyer'),
    
    path('blog', views.blog, name='blog'),
    path('add_blog', views.add_blog, name='add_blog'),
    path('edit_blog/<int:id>', views.edit_blog, name='edit_blog'),
    path('delete_blog/<int:id>', views.delete_blog, name='delete_blog'),    
    
    path('case_studies', views.casestudies, name='case_studies'),
    path('case_studies/add/', views.add_or_edit_case_study, name='add_case_study'),
    path('case_studies/edit/<int:pk>/', views.add_or_edit_case_study, name='edit_case_study'),
    
    path('types_Law', views.types_Law, name='types_law'),
    path('add-types-law', views.add_or_edit_types_law, name='add_types_law'),
    path('edit_types_law/<int:id>', views.add_or_edit_types_law, name='edit_types_law'),
    path('delete_types_law/<int:id>', views.delete_types_law, name='delete_types_law'),
        
    path('attorneys', views.attorneys, name='attorneys'),
    path('attorneys/add', views.add_team, name='add_attorney'),  
    path('attorneys/edit/<int:id>', views.edit_attorneys, name='edit_attorney'),  
    path('attorneys/delete/<int:id>', views.delete_Attorneys, name='delete_attorney'),
    
    path('add-case-categories', views.add_or_edit_case_categories, name='add_case_categories'),
    path('case_categories', views.case_catogory, name='case_categories'),
    path('case_categories_edit/<int:id>', views.add_or_edit_case_categories, name='edit_case_categories'),
    path('delete_case_categories/<int:id>', views.delete_case_categories, name='delete_case_categories'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("userapp.urls")),
    path('adminapp/', include("adminapp.urls")),
    path('clientapp/', include('clientapp.urls')),
    path('lawyerapp/', include("lawyerapp.urls")),
    path('accounts/', include('allauth.urls')),
]

adminapp/models.py
from django.db import models

# Create your models here.
class adminuser(models.Model):
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    
    
class lawyer(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    age = models.IntegerField(null=True, blank=True)
    password = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    
class Education(models.Model):
    lawyer = models.ForeignKey(lawyer, on_delete=models.CASCADE, related_name="educations")
    degree = models.CharField(max_length=100)
    expertise = models.CharField(max_length=25)
    institution = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    
    class Meta:
        ordering = ['-end_date']
    def __str__(self):
        return f"Education - {self.lawyer} - Degree Of -{self.degree}"
    
class Work_experience(models.Model):
    lawyer = models.ForeignKey(lawyer, on_delete=models.CASCADE, related_name="work_experiences")
    Court = models.CharField(max_length=100)
    Specialization = models.ForeignKey('userapp.case_categories',on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    def __str__(self):
        return f"Experience Of - {self.lawyer}"

adminapp/forms.py
from userapp.models import Attorneys,case_categories,Types_Law,case_studies,Blog
from adminapp.models import lawyer
from clientapp.models import clients
from userapp.models import User_Appointment
from django import forms


class Attorneys_edit_Form(forms.ModelForm):
    class Meta:
        model = Attorneys
        fields = ['name', 'profession', 'image']

class case_categories_edit_Form(forms.ModelForm):
    class Meta:
        model = case_categories
        fields = ['case_categories']
        
class types_edit_Form(forms.ModelForm):
    class Meta:
        model = Types_Law
        fields = ['law_tittle','point','detail','image']
        
class case_studies_Form(forms.ModelForm):
    class Meta:
        model = case_studies
        fields = ['case_studies_tittle','category','detail','case_studies_date','case_studies_image']
        
class blog_edit_Form(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['tittle','image','des']
        
class add_lawyer(forms.ModelForm):
    class Meta:
        model = lawyer
        fields = ['name','email','password']

class add_clients_forms(forms.ModelForm):
    class Meta:
        model = clients
        fields = ['name','email','password','lid']
        

class update_lawyer_profile(forms.ModelForm):
    class Meta:
        model = lawyer
        fields = ['name','age']
        
        
class edit_user_appointments(forms.ModelForm):
    class Meta:
        model = User_Appointment
        fields = ['name','email','lawyer']

adminapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from userapp.models import contact,Appointment,Attorneys,case_categories,Types_Law,Blog,case_studies,Client_Review,User_Appointment
from adminapp.models import adminuser,lawyer
from clientapp.models import clients
from .forms import Attorneys_edit_Form,case_categories_edit_Form,types_edit_Form,case_studies_Form,blog_edit_Form,add_lawyer,add_clients_forms,edit_user_appointments
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request,'adminapp/index.html')

def Show_contact(request):
    data = contact.objects.all
    return render(request,'adminapp/contact.html',{"data":data})

def Show_Appointment(request):
    data = Appointment.objects.all
    user_appointments = User_Appointment.objects.all
    return render(request,'adminapp/appointment.html',{"data":data,"User_Appointment":user_appointments})

def login(request):
    admin_session = request.session.get("admin_session", {})
    if admin_session.get("is_logged_in"):
        return redirect("adminapp/index")
    if request.method == "POST":  # Use request.method for correctness
        name = request.POST["name"]
        password = request.POST["password"]
        user = adminuser.objects.filter(name=name, password=password).count()
        if user > 0:
            request.session["admin_session"] = {
                "is_logged_in": True,
                "name": name
            }
            messages.success(request, "Login Successfully")
            return redirect("/adminapp/index")
        messages.error(request, "Wrong Username Or Password")
    return render(request, 'adminapp/login.html')

def logout_admin(request):
    if 'admin_session' in request.session:
        del request.session['admin_session']
    return redirect('/adminapp')

def blog(request):
    data = Blog.objects.all
    return render(request,'adminapp/blog.html',{"data":data})

def add_blog(request):
    if request.method == 'POST':
        form = blog_edit_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/adminapp/blog')
    else:
        form = blog_edit_Form()
    return render(request, 'adminapp/add_blog.html', {'form': form})

def edit_blog(request, id):
    blog = get_object_or_404(Blog, id=id)
    if request.method == 'POST':
        form = blog_edit_Form(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('/adminapp/blog')
    else:
        form = blog_edit_Form(instance=blog)
    return render(request, 'adminapp/add_blog.html', {'form': form})

def delete_blog(request, id):
    data = Blog.objects.get(id=id).delete()
    return redirect("/adminapp/blog")

def attorneys(request):
    data = Attorneys.objects.all
    return render(request,'adminapp/attorneys.html',{"data":data})

def case_catogory(request):
    data = case_categories.objects.all
    return render(request,'adminapp/case_categories.html',{"data":data})


def add_team(request):
    if request.method == 'POST':  
        form = Attorneys_edit_Form(request.POST, request.FILES)  
        if form.is_valid():  
            form.save()
            messages.success(request,'New Member Is Added Succesfully ')
            return redirect('/adminapp/attorneys')  
    else:
        form = Attorneys_edit_Form()  
    return render(request, 'adminapp/add_team.html', {'form': form})

def edit_attorneys(request,id):
    attorneys_instance = get_object_or_404(Attorneys, pk=id)
    if request.method == 'POST':
        form = Attorneys_edit_Form(request.POST, request.FILES, instance=attorneys_instance)
        if form.is_valid():
            form.save()
            return redirect('/adminapp/attorneys')
    else:
        form = Attorneys_edit_Form(instance=attorneys_instance)
    return render(request, 'adminapp/add_team.html', {'form': form})


def delete_Attorneys(request,id):
    data = Attorneys.objects.get(id=id).delete()
    messages.error(request,'Member Deleted Succesfully')
    return redirect("/adminapp/attorneys")

def add_or_edit_case_categories(request, id=None):
    instance = get_object_or_404(case_categories, pk=id) if id else None
    if request.method == 'POST':
        form = case_categories_edit_Form(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()  
            return redirect('adminapp/case_categories')
    else:
        form = case_categories_edit_Form(instance=instance)

    context = {
        'form': form,
        'is_edit': id is not None  
    }
    return render(request, 'adminapp/add_case_categories.html',{"form":form})
        
def delete_case_categories(request,id):
    data = case_categories.objects.get(id=id).delete()
    return redirect("/adminapp/case_categories")

def types_Law(request):
    data = Types_Law.objects.all
    return render(request,'adminapp/types_Law.html',{"data":data})

def add_or_edit_types_law(request, id=None):
    instance = get_object_or_404(Types_Law, pk=id) if id else None
    if request.method == 'POST':
        form = types_edit_Form(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('/adminapp/types_Law')
    else:
        form = types_edit_Form(instance=instance)

    context = {
        'form': form,
        'is_edit': id is not None  
    }
    return render(request, 'adminapp/add_types_law.html', {'form': form})


def delete_types_law(request,id):
    data = Types_Law.objects.get(id=id).delete()
    return redirect("/adminapp/types_Law")

def casestudies(request):
    data = case_studies.objects.all()
    return render(request,'adminapp/casestudies.html',{"data":data})

def add_or_edit_case_study(request, pk=None):
    instance = get_object_or_404(case_studies, pk=pk) if pk else None
    if request.method == "POST":
        form = case_studies_Form(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()  
            return redirect('/adminapp/case_studies')  
    else:
        form = case_studies_Form(instance=instance)

    context = {
        'form': form,
        'is_edit': pk is not None  
    }
    return render(request, 'adminapp/add_case_studies.html', context)

def reviews(request):
    data = Client_Review.objects.all
    return render(request,'adminapp/reviews.html',{"data":data})

def lawyers(request):
    data = lawyer.objects.all
    return render(request,'adminapp/lawyer.html',{"data":data})

def delete_lawyer(request,id):
    data = lawyer.objects.get(id=id).delete()
    return redirect(request,"adminapp/lawyer.html")

def add_new_lawyer(request):
    if request.method == 'POST':  
        form = add_lawyer(request.POST)  
        if form.is_valid():  
            form.save()  
            return redirect('/adminapp/lawyer')  
    else:
        form = add_lawyer()  
    return render(request, 'adminapp/add_lawyer.html', {'form': form})

def client(request):
    data = clients.objects.all()
    return render(request,'adminapp/clients.html',{"data":data})


def add_or_edit_client(request, pk=None):
    instance = get_object_or_404(clients, pk=pk) if pk else None
    if request.method == "POST":
        form = add_clients_forms(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()  
            return redirect('/adminapp/clients')  
    else:
        form = add_clients_forms(instance=instance)
        
        context = {
        'form': form,
        'is_edit': pk is not None  
    }
    return render(request, 'adminapp/add_client.html', context)

def delete_client(request,id):
    data = clients.objects.get(id=id).delete()
    return render(request, "adminapp/clients.html")

def edit_lawyer(request,id):
    lawyer_instance = get_object_or_404(lawyer, pk=id)
    if request.method == 'POST':
        form = add_lawyer(request.POST, request.FILES, instance=lawyer_instance)
        if form.is_valid():
            form.save()
            return redirect('/adminapp/lawyer')
    else:
        form = add_lawyer(instance=lawyer_instance)
    return render(request, 'adminapp/add_lawyer.html', {'form': form})

def edit_appointments(request,id):
    appointment_instance = get_object_or_404(User_Appointment, pk=id)
    if request.method =="POST":
        form = edit_user_appointments(request.POST,instance=appointment_instance)
        if form.is_valid():
            form.save()
            return redirect('/adminapp/appointment')
        else:
            return render(request, 'adminapp/edit_appointments.html',{'form':form})
    else:
        form = edit_user_appointments(instance=appointment_instance)
    return render(request,"adminapp/edit_user_appointments.html", {'form':form})

def demo(request):
    return render(request,'adminapp/demo.html')

templates/adminapp/add_blog.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Admin Panel</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'adminapp/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'adminapp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'adminapp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        {% include 'adminapp/sidebar.html' %}

        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            {% include 'adminapp/navbar.html' %}
            <!-- Navbar End -->

            
            <!-- Blank Start -->
            <div class="col-sm-12 col-xl-6">
                <div class="rounded h-100 p-4">
                  {% if form.instance.pk %} 
                  Edit Blog
                  {% else %} 
                  Add New Blog
                  {% endif %}
                  <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %} {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="/adminapp/blog" class="btn btn-secondary">Back</a>
                  </form>
                </div>
              </div>
            <!-- Blank End -->

            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Rights Reserved.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->

    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'adminapp/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'adminapp/js/main.js' %}"></script>
</body>

</html>

templates/adminapp/add_case_categories.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Admin Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />

    <!-- Libraries Stylesheet -->
    <link
      href="{% static 'adminapp/lib/owlcarousel/assets/owl.carousel.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'adminapp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}"
      rel="stylesheet"
    />

    <!-- Customized Bootstrap Stylesheet -->
    <link
      href="{% static 'adminapp/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <!-- Template Stylesheet -->
    <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
      <!-- Spinner Start -->
      <div
        id="spinner"
        class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center"
      >
        <div
          class="spinner-border text-primary"
          style="width: 3rem; height: 3rem"
          role="status"
        >
          <span class="sr-only">Loading...</span>
        </div>
      </div>
      <!-- Spinner End -->

      <!-- Sidebar -->
      {% include 'adminapp/sidebar.html' %}

      <!-- Content Start -->
      <div class="content">
        <!-- Navbar Start -->
        {% include 'adminapp/navbar.html' %}
        <!-- Navbar End -->

        <!-- Update Form Start -->
        <div style="display: flex; justify-content: left; align-items: center; height: 40vh; margin: 25px;">
          <div style="width: 50%; background-color:rgb(222, 228, 231); padding: 20px; border-radius: 8px; box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);">
        <div class="col-sm-12 col-xl-6">
          <div class="rounded h-100 p-4">
            {% if form.instance.pk %} 
            Edit  
            {% else %} 
            Add New  
            {% endif %}
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %} {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Save</button>
              <a href="/adminapp/case_categories" class="btn btn-secondary">Back</a>
            </form>
          </div>
        </div>
        </div>
        </div>
        <!-- Update Form End -->
      </div>
      <!-- Content End -->
    </div>

    <!-- Back to Top -->

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'adminapp/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'adminapp/js/main.js' %}"></script>
  </body>
</html>

templates/adminapp/edit_user_appointments.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Admin Panel</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'adminapp/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'adminapp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'adminapp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'adminapp/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        {% include 'adminapp/sidebar.html' %}

        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            {% include 'adminapp/navbar.html' %}
            <!-- Navbar End -->

            
            <!-- Blank Start -->
            <div style="display: flex; justify-content: left; align-items: center; height: 40vh; margin: 25px;">
                <div style="width: 50%; background-color:rgb(222, 228, 231); padding: 20px; border-radius: 8px; box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);">
                  {% if form.instance.pk %} 
                  Edit Details 
                  {% else %} 
                  Add New Member 
                  {% endif %}
                  <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                
                    <!-- Name (Read-Only) -->
                    <p>
                        <label for="id_name">Name:</label>
                        <input type="text" name="name" value="{{ form.name.value }}" readonly class="form-control">
                    </p>
                
                    <!-- Email (Read-Only) -->
                    <p>
                        <label for="id_email">Email:</label>
                        <input type="email" name="email" value="{{ form.email.value }}" readonly class="form-control">
                    </p>
                
                    <!-- Lawyer (Editable) -->
                    <p>
                        <label for="id_lawyer">Lawyer:</label>
                        {{ form.lawyer }}
                    </p>
                
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="/adminapp/appointment" class="btn btn-secondary">Back</a>
                </form>
                
                </div>
              </div>
            <!-- Blank End -->

            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Rights Reserved.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->

    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'adminapp/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'adminapp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'adminapp/js/main.js' %}"></script>
</body>

</html>